### ISSUE TITLE
Package Updates

### ISSUE THREAD

**Issue by chrisVillanueva** [infrastructure-components/visit-count#3]
I cloned this repo and installed packages.  npm reports several outdated packages:

```
found 36 vulnerabilities (20 low, 3 moderate, 13 high) in 1977 scanned packages
  run `npm audit fix` to fix 21 of them.
  15 vulnerabilities require manual review. See the full report for details.
```

Will there be any updates to resolve this?  Or should I submit a PR?

**Comment by frankzickert** [comment]
I updated the dependencies as far as there were no compatibility issues
